/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.eavp.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSTLScopeProvider extends DelegatingScopeProvider {
}
